### PR TITLE
Reworked coroutines implmentation

### PR DESCRIPTION
**Pull request by SirePi**
This is a reworked implementation of the first, much more complex implementation (see PR #674) and takes into account all the comments to the previous version.
It's been made as a separate PR to reduce the number of commits affecting the changes.

### CODE REVIEW

**Comment by SirePi** [comment]
Huuuu.. did I do the bad thing?

**Comment by Barsonax** [comment]
thats a awful lot of merge commits?

**Comment by SirePi** [comment]
*In theory* I just got back on par with the current status of the master branch.. don't know if it's still ok or I should just redo the PR. @ilexp?

**Comment by Barsonax** [comment]
Those commits from 2015 shouldnt be there. I cannot find the hashes of those commits either. What did you do O_o.

**Comment by Barsonax** [comment]
It seems that the release branch that you merged into your branch contains alot of merge commits (all the way to 2015) that are not present in the master branch:
image

I think what went wrong here is in fact merging the release branch into your branch. I think you should redo it and instead of merging the release branch to your branch you should merge the master branch into your branch.

**Comment by SirePi** [comment]
Ah damn.. got the wrong one.. oh well, a new PR it is 😓

**Pull request closed without merging**
