### PR TITLE
Fixed FlapOrDie content location

### PR DESCRIPTION
**Pull request by SirePi**

### CODE REVIEW

**Comment by ilexp** [comment]
Note to self: Adjust the .nuspec file after merging this.
Note to self: Read up on git whether it's possible to "cut out" the first two "Implement X / Revert X" commits for added cleanliness.

**Comment by SirePi** [comment]
Sorry about the added/revert.. I commited my version with the key-based sprite atlas in the wrong branch

**Comment by ilexp** [comment]
I merged this using a [cherry-pick on the relevant commit](https://github.com/AdamsLair/duality/commit/7b2bc87fa7676d00fbdd27dfe5e1e3cb19e6a71a) from your repository. However, because of the accidental commit / revert and me skipping them, you will not be able to submit merge-able Pull Requests in the future.

To fix this, you'll need to reset your forks master branch to the state of the main repository. I have done that once, so I know a git feature like that exists, but I'm not sure how I did that back then anymore. Something like the following:

- In your local repository, reset current branch to the commit before the ones you want to discard. In your case, the one before adding the key-atlas to master. That should be a hard reset.
- Force-push of your local repository back to github.
- Pull from github to double-check all is well.
- Merge the latest master branch from the main repo. You should automatically get the commit I cherry-picked back.

Not entirely sure, you should probably double-check this.

**Comment by SirePi** [comment]
No worries, I can simply erase the repo and refork it.

**Comment by ilexp** [comment]
> No worries, I can simply erase the repo and refork it.

But.. your other branches?

**Comment by SirePi** [comment]
Well, I still managed to merge your working copy with mine, so I'm pretty confident it's ok. We'll see next time :smile:

**Comment by ilexp** [comment]
> Well, I still managed to merge your working copy with mine, so I'm pretty confident it's ok. We'll see next time :smile: 

I think that might not be the _main_ problem. If you merge my branch back into yours, you will still have those two commits in your master branch. Whenever you submit a new PR, I will have to do cherry-picking (potentially commit-by-commit?) to avoid getting those two old commits into my master branch anyway.

You might need to do a hard-reset to your master branch to prevent that, but as you said: We'll see next time :smile:

**Comment by looperhacks** [comment]
The next time you have more commits than you want, you might want to try squashing them so they appear as one commit. http://stackoverflow.com/q/5189560/1582846

But don't do this on a shared branch or else everyone who cloned your branch will encounter problems.

**Pull request closed without merging**
