### PR TITLE
Fix display of version info to no longer include launcher version.

### PR DESCRIPTION
**Pull request by TheRut**
Found this bug while exploring the codebase, which was preventing the About dialog from displaying.

### CODE REVIEW

**Comment by Barsonax** [comment]
Thanks for making the PR. 

I was able to reproduce this and found that I broke this in 5e484144224376f69aa1754ae728495d6ea76e28. I don't think we should put a try catch around this though but rather just change `labelVersionData.text` to be `"{0}\r\n{1}"` instead of `"{0}\r\n{1}\r\n{2}"` so that the error won't happen anymore.

**Comment by TheRut** [comment]
Removed the try/catch. I did leave the update to the form layout so that the click-to-copy functionality captures the version information now (which I believe was the intent).

**Comment by Barsonax** [comment]
Ok, will try to test this soon

**Review by ilexp — APPROVED** [review]
Works as expected. @Barsonax (Squash-)Merge as you see fit 👍

**Comment by Barsonax** [comment]
Squash merged from mobile :)

**Pull request merged**
