### PR TITLE
#595

### PR DESCRIPTION
**Pull request by Barsonax**

### CODE REVIEW

**Comment by ilexp** [comment]
Will take a look at this later, but might take a bit longer than usually for a PR of this size. This is a `master` commit on the `Transform` component after all, so we need to make sure there's absolutely no added bug potential in there.

**Comment by ilexp** [comment]
Simplified tests and Transform implementation a bit, made some minor code style adjustments, handled serialization and cloning for the new field and used it to optimize some more Transform methods and properties.

Still need to test some more real-world cases before merging.

**Comment by Barsonax** [comment]
There is still room for optimization in UpdateAbs. It currently calls MathF.GetTransformDotVec which builds up a rotationmatrix and it also calls UpdateRotationDirAbs which updates the rotationDir. This is a duplicate sin/cos operation.

**Comment by ilexp** [comment]
> There is still room for optimization in UpdateAbs. It currently calls MathF.GetTransformDotVec here which builds up a rotationmatrix and it also calls UpdateRotationDirAbs here which updates the rotationDir. This is a duplicate sin/cos operation I believe.

Nice find 👍 Will take care of it, still have the code open for testing anyway.

**Pull request merged**
