### PR TITLE
Adding XAdvance

### PR DESCRIPTION
**Pull request by mika76**
Here's my attempt :smile: 

I've Added the AdvanceX property and moved the calculation of it to the font renderer instead of the update kernings method. I've also had to update your included fonts. Let me know what you think.

### CODE REVIEW

**Comment by ilexp** [comment]
Quickly looked through the code, I think the implementation isn't quite there yet:

1. Spacing is a Font-wide setting that still needs to be applied as before. Users might want to adjust this, it is not replaced by the new explicit `AdvanceX` but needs to interact properly.
2. The Monospace setting can't go away either. Same as with spacing, needs to interact properly with the new `AdvanceX`, rather than being replaced.
3. Where does the "magic equation" `(internalFont.Size / 10.0f)` come from?

On a different note, updating the embedded Fonts is definitely required, good thinking!

**Comment by mika76** [comment]
> 3 

It comes from the charSpacinng calculation in the current font implementation. As far as I could see bmfont included spacing in the xadvance? It all looks good when rendering. Monospace still seems to work too.

**Comment by ilexp** [comment]
Actually, we need to do something about backwards compatibility in general, now that I think about it. Instead of updating the internal Font, there needs to be some preparation in `Font.OnLoaded` that checks if a sample set of glyphs has a non-zero `AdvanceX` value and auto-calculates it based on width and offset if not.

**Comment by mika76** [comment]
Ah OK I'll have a look at that.

**Comment by ilexp** [comment]
> It comes from the charSpacinng calculation in the current font implementation.

Ah. In that case, it should stay in the spacing variable so it's user-adjustable on a per-Font level.

> Ah OK I'll have a look at that.

Great, thanks :+1:

**Comment by mika76** [comment]
Spacing was always calculated as far as I saw and was not user changeable...

**Comment by mika76** [comment]
It's in the size setter.

**Comment by ilexp** [comment]
> Spacing was always calculated as far as I saw and was not user changeable...

> It's in the size setter.

It's default is auto-calculated, but it's [adjustable by the user](https://github.com/AdamsLair/duality/blob/master/Duality/Resources/Font.cs#L207-L211) using the `CharSpacing` property in the object inspector.

**Comment by mika76** [comment]
Ah of course. Ok I'll add it back. 

In pixel fonts it seems to me that spacing is included in the xadvance though, do you think I should negate it when importing?

**Comment by ilexp** [comment]
> In pixel fonts it seems to me that spacing is included in the xadvance though, do you think I should negate it when importing?

I think for now you could set `CharSpacing` property to zero right after calling `SetGlyphData` in your importer. Since `Size` is never set for BMFonts, it won't jump back to the hardcoded default and you won't have to adjust the (correctly imported) x-advance values.

**Pull request closed without merging**
