### PR TITLE
#711 Updated nuget.core to 2.14

### PR DESCRIPTION
**Pull request by Barsonax**
TODO:
- [x] Update `nuget.core` to 2.14 to support netstandard (discovered in #710)
- [x] Find out why IsLatestVersion is wrongly set to true for AdamsLair.Duality.TestPlugin 1.0.0.0 in PackageManagerTests.GetLatestDualityPackages
- [x] Come up with a fix for the above problem
- [x] Verify package installs with the official sample packages work as expected.
- [x] Verify package installs with multi-framework targets work as expected (for example Singularity v0.9)
- [x] Build a binary download .zip with the new NuGet and verify both install and restore work as expected.
- [ ] After the merge, upload a new binary .zip to replace the [current one under releases](https://github.com/AdamsLair/duality/releases/tag/v3.0).

### CODE REVIEW

**Comment by ilexp** [comment]
Related issue is #711, to be closed when this is merged.

**Comment by ilexp** [comment]
Cleared block from issue #716.

**Comment by ilexp** [comment]
What's the state of this PR, e.g. which are the ToDos that are still to be done before review? Only seeing "Test Test Test" in the main comment, not sure what exactly that means 😄

**Comment by Barsonax** [comment]
There seems to be a breaking change in nuget:
image

Also VertexBatchTest.Locking fails for me locally (but not on appveyor?) not sure why.

**Comment by Barsonax** [comment]
IsLatestVersion is somehow wrongly set on the 1.0.0.0 TestPlugin package:
image

**Comment by Barsonax** [comment]
Modified code in PackageManager.cs a bit to catch the bug earlier in the process. Seems to have something to do with the LazyLocalPackageRepository:
image

**Comment by Barsonax** [comment]
Nuget v2.8.5 is the last version that doesn't exhibit this behavior. All versions from v2.8.6 on seem to have this bug.

**Comment by Barsonax** [comment]
Ah I see we have a custom piece of code that sets the is latest. This piece of code expects a LocalPackageRepository to be present. However from nuget 2.8.6 on its now wrapped in a LazyLocalPackageRepository. Fix should be easy.

**Comment by Barsonax** [comment]
TODO:
- perform some real tests to verify the package manager is working as expected.

**Comment by ilexp** [comment]
Great work, looking forward to the test results 👍 

> Also VertexBatchTest.Locking fails for me locally (but not on appveyor?) not sure why.

This could be related to semi-unsafe code, we should verify it's not an x86 / x64 disparity or something like that. Can you open a new issue detailing the exact failure, as well as the test init logs regarding processor architecture and process modes?

**Comment by Barsonax** [comment]
Did the following tests:
- Install singularity 0.9, this is a multi framework package that targets net 4.5.2 and netstandard 2.0. It picks the net 4.5.2 version which is correct!
- Installed some other package such as tilemaps or the sample packages.

**Comment by ilexp** [comment]
> @ilexp I guess you want to take a look as well before merging this?

Will do as soon as I manage.

**Comment by ilexp** [comment]
## Progress

- Fixed an unrelated, but blocking bug in master branch package management.
- Debug-stepped through unit tests for packages and verified the new netstandard framework can now be parsed properly by NuGet.
- Tested package install, uninstall and restore with various official and non-official plugin and sample packages.

## ToDo

- Merge back to master, bump version numbers and trigger a new binary release.
- After the merge, upload a new binary .zip to replace the current one under releases.
- Do a final "out in the wild" test.

Looks fine to me, I'd say we're ready for merge. Will proceed when I find the next sufficiently large time frame to do so without a rush.

**Comment by ilexp** [comment]
> Also VertexBatchTest.Locking fails for me locally (but not on appveyor?) not sure why.

@Barsonax Any info on this? Is this still an issue?

**Comment by Barsonax** [comment]
No that test still fails. Created issue about it: https://github.com/AdamsLair/duality/issues/719

Seems to have nothing to do with this PR so lets merge this and look into that issue afterwards.

**Comment by ilexp** [comment]
> Seems to have nothing to do with this PR so lets merge this and look into that issue afterwards.

Agreed. Proceeding as outlined above and as time allows 👍

**Comment by ilexp** [comment]
Merged, triggered a package release, and updated the download package.

**Pull request merged**
