### PR TITLE
#291 Fixing pickshapes code

### PR DESCRIPTION
**Pull request by Barsonax**
#291 

Tested the code using the unit tests I made and opened up a duality instance and used code in the https://github.com/AdamsLair/duality/files/139614/PickShapesBugDemo.zip to test this. Could not find cases where I got false results except when changing the scale of the transform while the game is running but this is another issue and this PR is quite big already.

### CODE REVIEW

**Comment by ilexp** [comment]
No review yet, but code-related continued discussion from issue #291:

> Also compared the performance and the new version is actually slower currently. It varies but I have seen cases where its twice as slow. Ill see if I can get it faster.
>
> EDIT: after looking through the old implementation it seems to be doing only collisions between the AABB's? No wonder its faster.

Can you profile to see where the bottleneck is and optimize the new version?

**Comment by Barsonax** [comment]
Currently going through the code to fix any unnecessary calculations and do a bit of cleanup.

**Comment by Barsonax** [comment]
It seems a lot of performance is being eaten by GetWorldPoint and GetLocalPoint. Upon closer inspection it calls into TransformCoord which does a Math.Sin and a Math.Cos which are quite expensive operations (over 100x slower than multiplication in my own testing).

On a side note isn't it possible to just multiply the vector with a transformation matrix? I expect that to be a lot faster.

**Comment by ilexp** [comment]
Wait a sec - you didn't seem to use the [Farseer methods](https://github.com/AdamsLair/farseerduality/blob/65b1396bf03f83706fe740c097e56b25053d058a/Collision/Collision.cs#L761) for the check [as we discussed earlier](https://github.com/AdamsLair/duality/issues/291#issuecomment-335547689) - what's the reason for this? I know the contact checks themselves were inaccessible, but the static versions are, right? Pretty sure they're already optimized well and I don't want to duplicate this functionality if we already have it just sitting there.

**Comment by ilexp** [comment]
Took a quick look at Farseer code to see how those methods are used and make sure I'm not asking for something stupid 😄

Seems like `Manifold` and `Transform` are public, and you can get each bodies `Transform` using its public `GetTransform` method. So theoretically, you could [do the same as Farseer does](https://github.com/AdamsLair/farseerduality/blob/65b1396bf03f83706fe740c097e56b25053d058a/Dynamics/Contacts/Contact.cs#L293), except not using `Xf` directly, but doing a detour through `GetTransform`. 

Using this approach, we'd just re-use the existing Farseer code and existing data structures, so there would be no need for any coordinate transformation beyond that needed for a constructing a single temporary `PolygonShape` in the beginning of the method. With that, there's also be no need for a separate `Box` class, and we'd have the code in place to extend the collision check easily in the future - for example towards non-rect shapes.

API-wise, you could operate directly on the Farseer bodies and iterate their fixtures / shapes, so we wouldn't even need any changes to existing `ShapeInfo` API, which would lower the complexity of the PR a bit too.

**Comment by Barsonax** [comment]
Its not clear to me how I could use the farseer code here. I tried it for polygons but it did not detect any collisions.

**Comment by Barsonax** [comment]
I have implemented the PickShapes using farseer for polygons and circles. See #579

**Comment by ilexp** [comment]
Looks much better :) Closing this PR, as it is superseded by #579.

**Pull request closed without merging**
