### PR TITLE
revised project structure with dualityeditor still at the root

### PR DESCRIPTION
**Pull request by Barsonax**
Revision of #823

Decided to keep DualityEditor/DualityLauncher in the root for now as that doesn't require much changes in duality:
```
[Project Folder]
|
+- [Project].sln
|
+- DualityEditor.exe
+- Data
+- Plugins
+- all the other project files and binaries
|
+- Import
|
+- Source
   +- Launchers
      +- GameLauncher
      +- GameEditor
   +- Plugins
      +- GamePlugin
```

### CODE REVIEW

**Comment by ilexp** [comment]
Is this still WiP? What's needed to complete this?

**Comment by Barsonax** [comment]
Now its ready, also removed auto creating the source folder and added a check around the source folder filewatcher to prevent it from raising a error if the source folder does not exist.

I believe this is more inline with the role of source folder in v4 where duality no longer manages it but just integrates with it.

**Comment by ilexp** [comment]
Looking good, approval still stands 👍

**Comment by ilexp** [comment]
Can the feature branch be deleted, or do you still need it?

**Pull request merged**
