### PR TITLE
#365 Tilemap tile data tags

### PR DESCRIPTION
**Pull request by Barsonax**
TODO:
- [ ] Convert the List to a dictionary in the compilation step
- [ ] Provide a more user friendly way of assigning values to tiles
- [ ] Clean up

### CODE REVIEW

**Comment by ilexp** [comment]
This is a WiP issue, correct? Ping me when you reach a ready-for-review state, or have questions regarding the implementation 👍

**Comment by Barsonax** [comment]
Having a bit of a lack of time lately between work, university and pathfindax (and actually having some free time) so not sure when I will be able to work on this one.

**Comment by ilexp** [comment]
Thanks for the info 👍 If there's no ETA for further work on this right now, I'd prefer to close the PR and re-open it when there is.

**Comment by Barsonax** [comment]
Sure

**Pull request closed without merging**
